# Snooker players in pl.wikipedia
SELECT DISTINCT 
?item 
?country 
?countryLabel 
?LabelEN
?LabelPL
?page_titlePL
WHERE {
  ?item wdt:P31 wd:Q5;
    wdt:P106 wd:Q17165321;
    wdt:P1532 ?country.
  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "pl".
    ?country rdfs:label ?countryLabel.
  }
  OPTIONAL {
	# pl.wiki article title
    ?article schema:about ?item;
      schema:isPartOf <https://pl.wikipedia.org/>;
      schema:name ?page_titlePL.
	# Polish WD label
    ?item rdfs:label ?LabelPL FILTER((LANG(?LabelPL)) = "pl").
  }
  # English WD label
  ?item rdfs:label ?LabelEN FILTER((LANG(?LabelEN)) = "en").
}
ORDER BY ASC(?country) ASC(?LabelEN)
# LIMIT 300
