snook.players = [
	new snook.player ("Khaled Belaid Abumdas", "", 'LBY'),

	new snook.player ("Amine Amiri", "", 'MAR'),
	new snook.player ("Hakima Kissai", "", 'MAR'),
	new snook.player ("Yassine Bellamine", "", 'MAR'),
	new snook.player ("Youssra Matine", "", 'MAR'),

	new snook.player ("Ang\u00e9lique Vialard", "", 'FRA'),
	new snook.player ("Brian Ochoiski", "", 'FRA'),
	new snook.player ("Niel Vincent", "", 'FRA'),

	new snook.player ("Au Chi-wai", "", 'CHN'),
	new snook.player ("Bai Langning", "", 'CHN'),
	new snook.player ("Bai Yulu", "", 'CHN'),
	new snook.player ("Bi Zhu Qing", "", 'CHN'),
	new snook.player ("Cao Xinlong", "", 'CHN'),
	new snook.player ("Cao Yupeng", "", 'CHN'),
	new snook.player ("Chang Bingyu", "", 'CHN'),
	new snook.player ("Chen Feilong", "", 'CHN'),
	new snook.player ("Chen Zhe", "", 'CHN'),
	new snook.player ("Chen Zifan", "", 'CHN'),
	new snook.player ("Ding Junhui", "", 'CHN'),
	new snook.player ("Fan Zhengyi", "", 'CHN'),
	new snook.player ("Fang Xiongman", "", 'CHN'),
	new snook.player ("Gao Yang", "", 'CHN'),
	new snook.player ("Gary Kwok", "", 'CHN'),
	new snook.player ("Guo Hua", "", 'CHN'),
	new snook.player ("He Guoqiang", "", 'CHN'),
	new snook.player ("Jiang Jun", "", 'CHN'),
	new snook.player ("Jin Long", "", 'CHN'),
	new snook.player ("Ju Reti", "", 'CHN'),
	new snook.player ("Lei Peifan", "", 'CHN'),
	new snook.player ("Li Hang", "", 'CHN'),
	new snook.player ("Li Yan", "", 'CHN'),
	new snook.player ("Li Yuan", "", 'CHN'),
	new snook.player ("Liang Wenbo", "", 'CHN'),
	new snook.player ("Liu Chuang", "", 'CHN'),
	new snook.player ("Liu Song", "", 'CHN'),
	new snook.player ("Long Zehuang", "", 'CHN'),
	new snook.player ("Lu Chenwei", "", 'CHN'),
	new snook.player ("Lu Ning", "", 'CHN'),
	new snook.player ("Luo Honghao", "", 'CHN'),
	new snook.player ("Lyu Haotian", "", 'CHN'),
	new snook.player ("Ma Hailong", "", 'CHN'),
	new snook.player ("Marco Fu", "", 'CHN'),
	new snook.player ("Mei Xiwen", "", 'CHN'),
	new snook.player ("Niu Zhuang", "", 'CHN'),
	new snook.player ("Pang Junxu", "", 'CHN'),
	new snook.player ("Pang Weiguo", "", 'CHN'),
	new snook.player ("Peng Yisong", "", 'CHN'),
	new snook.player ("Rouzi Maimaiti", "", 'CHN'),
	new snook.player ("Shi Chunxia", "", 'CHN'),
	new snook.player ("Si Jiahui", "", 'CHN'),
	new snook.player ("Tian Pengfei", "", 'CHN'),
	new snook.player ("Wang Yuchen", "", 'CHN'),
	new snook.player ("Wu Yize", "", 'CHN'),
	new snook.player ("Xiao Guodong", "", 'CHN'),
	new snook.player ("Xing Zihao", "", 'CHN'),
	new snook.player ("Xu Si", "", 'CHN'),
	new snook.player ("Yan Bingtao", "", 'CHN'),
	new snook.player ("Yu Delu", "", 'CHN'),
	new snook.player ("Yuan Sijun", "", 'CHN'),
	new snook.player ("Zhang Anda", "", 'CHN'),
	new snook.player ("Zhang Jiankang", "", 'CHN'),
	new snook.player ("Zhang Yong", "", 'CHN'),
	new snook.player ("Zhao Jianbo", "", 'CHN'),
	new snook.player ("Zhao Xintong", "", 'CHN'),
	new snook.player ("Zhou Yuelong", "", 'CHN'),

	new snook.player ("Baianinho de Mau\u00e1", "", 'BRA'),
	new snook.player ("Igor Figueiredo", "", 'BRA'),
	new snook.player ("Itaro Santos", "", 'BRA'),
	new snook.player ("Rui Chap\u00e9u", "", 'BRA'),
	new snook.player ("Victor Sarkis", "", 'BRA'),

	new snook.player ("Aleksandra Guleikova", "", 'RUS'),
	new snook.player ("Anastasia Nechaeva", "", 'RUS'),
	new snook.player ("Anna Mazhirina", "", 'RUS'),
	new snook.player ("Kristina Tkach", "", 'RUS'),

	new snook.player ("Alain Robidoux", "", 'CAN'),
	new snook.player ("Bernie Mikkelsen", "", 'CAN'),
	new snook.player ("Bob Chaperon", "", 'CAN'),
	new snook.player ("Brady Gollan", "", 'CAN'),
	new snook.player ("Cliff Thorburn", "", 'CAN'),
	new snook.player ("Dean Mellway", "", 'CAN'),
	new snook.player ("Floyd Ziegler", "", 'CAN'),
	new snook.player ("Frank Jonik", "", 'CAN'),
	new snook.player ("Gary Natale", "", 'CAN'),
	new snook.player ("George Chenier", "", 'CAN'),
	new snook.player ("Gerry Watson", "", 'CAN'),
	new snook.player ("Gino Rigitano", "", 'CAN'),
	new snook.player ("Jim Bear", "", 'CAN'),
	new snook.player ("Jim Wych", "", 'CAN'),
	new snook.player ("Joe Cagianello", "", 'CAN'),
	new snook.player ("John Bear", "", 'CAN'),
	new snook.player ("Kevin Robitaille", "", 'CAN'),
	new snook.player ("Kirk Stevens", "", 'CAN'),
	new snook.player ("Leo Levitt", "", 'CAN'),
	new snook.player ("Marcel Gauvreau", "", 'CAN'),
	new snook.player ("Mario Morra", "", 'CAN'),
	new snook.player ("Maryann McConnell", "", 'CAN'),
	new snook.player ("Natalie Stelmach", "", 'CAN'),
	new snook.player ("Paul Thornley", "", 'CAN'),
	new snook.player ("Sue LeMaich", "", 'CAN'),
	new snook.player ("Tom Finstad", "", 'CAN'),
	new snook.player ("Wayne Sanderson", "", 'CAN'),

	new snook.player ("Keishin Kamihashi", "", 'JPN'),

	new snook.player ("Alexander Widau", "", 'DEU'),
	new snook.player ("Diana Schuler", "", 'DEU'),
	new snook.player ("Diana Stateczny", "", 'DEU'),
	new snook.player ("Felix Frede", "", 'DEU'),
	new snook.player ("Frank Schr\u00f6der", "", 'DEU'),
	new snook.player ("Lasse M\u00fcnstermann", "", 'DEU'),
	new snook.player ("Lukas Kleckers", "", 'DEU'),
	new snook.player ("Michael Schnabel", "", 'DEU'),
	new snook.player ("Patrick Einsle", "", 'DEU'),
	new snook.player ("Peter Wagner", "", 'DEU'),
	new snook.player ("Richard Wienold", "", 'DEU'),
	new snook.player ("Roman Dietzel", "", 'DEU'),
	new snook.player ("Sascha Diemer", "", 'DEU'),
	new snook.player ("Sascha Lippe", "", 'DEU'),
	new snook.player ("Simon Lichtenberg", "", 'DEU'),
	new snook.player ("Stefan Kasper", "", 'DEU'),
	new snook.player ("Thomas Hein", "", 'DEU'),

	new snook.player ("Brynjar Valdimarsson", "", 'ISL'),
	new snook.player ("E\u00f0var\u00f0 Matth\u00edasson", "", 'ISL'),
	new snook.player ("Gary Hardiman", "", 'ISL'),
	new snook.player ("Indika Dodangoda", "", 'ISL'),
	new snook.player ("J\u00f3hannes B. J\u00f3hannesson", "", 'ISL'),
	new snook.player ("J\u00f3hannes R. J\u00f3hannesson", "", 'ISL'),
	new snook.player ("Kristj\u00e1n Helgason", "", 'ISL'),
	new snook.player ("Peter Daubney", "", 'ISL'),
	new snook.player ("\u00c1sgeir \u00c1sgeirsson", "", 'ISL'),

	new snook.player ("Andres Petrov", "", 'EST'),

	new snook.player ("Peter Mans", "", 'RSA'),

	new snook.player ("Anita Rizzuti", "", 'NOR'),
	new snook.player ("Bj\u00f8rn L\u2019Orange", "", 'NOR'),
	new snook.player ("Christopher Watts", "", 'NOR'),
	new snook.player ("Kurt Maflin", "", 'NOR'),

	new snook.player ("Adam Davies", "", 'ENG'),
	new snook.player ("Adam Duffy", "", 'ENG'),
	new snook.player ("Adam Wicheard", "", 'ENG'),
	new snook.player ("Adrian Gunnell", "", 'ENG'),
	new snook.player ("Adrian Rosa", "", 'ENG'),
	new snook.player ("Alan Trigg", "", 'ENG'),
	new snook.player ("Albert Brown", "", 'ENG'),
	new snook.player ("Albert Cope", "", 'ENG'),
	new snook.player ("Alec Brown", "", 'ENG'),
	new snook.player ("Alec Mann", "", 'ENG'),
	new snook.player ("Alex Davies", "", 'ENG'),
	new snook.player ("Alfred Burden", "Alfie Burden", 'ENG'),
	new snook.player ("Allan Taylor", "", 'ENG'),
	new snook.player ("Allison Fisher", "", 'ENG'),
	new snook.player ("Allister Carter", "", 'ENG'),
	new snook.player ("Andrew Cairns", "", 'ENG'),
	new snook.player ("Andrew Higginson", "", 'ENG'),
	new snook.player ("Andrew Norman", "", 'ENG'),
	new snook.player ("Andy Hicks", "", 'ENG'),
	new snook.player ("Andy Lee", "", 'ENG'),
	new snook.player ("Andy Yates", "", 'ENG'),
	new snook.player ("Ann-Marie Farren", "", 'ENG'),
	new snook.player ("Anthony Bolsover", "", 'ENG'),
	new snook.player ("Anthony Hamilton", "Anthony Hamilton (snookerzysta)", 'ENG'),
	new snook.player ("Anthony Harris", "", 'ENG'),
	new snook.player ("Antony Bolsover", "", 'ENG'),
	new snook.player ("Ashley Carty", "", 'ENG'),
	new snook.player ("Ashley Hugill", "", 'ENG'),
	new snook.player ("Ashley Wright", "", 'ENG'),
	new snook.player ("Barry Hawkins", "", 'ENG'),
	new snook.player ("Barry Pinches", "", 'ENG'),
	new snook.player ("Barry West", "", 'ENG'),
	new snook.player ("Ben Hancorn", "", 'ENG'),
	new snook.player ("Ben Harrison", "", 'ENG'),
	new snook.player ("Ben Woollaston", "", 'ENG'),
	new snook.player ("Bernard Bennett", "", 'ENG'),
	new snook.player ("Bill Oliver", "", 'ENG'),
	new snook.player ("Billy Joe Castle", "", 'ENG'),
	new snook.player ("Bob Harris", "", 'ENG'),
	new snook.player ("Bradley Jones", "", 'ENG'),
	new snook.player ("Brandon Sargeant", "", 'ENG'),
	new snook.player ("Brian Morgan", "", 'ENG'),
	new snook.player ("Brian Rowswell", "", 'ENG'),
	new snook.player ("Brian Salmon", "", 'ENG'),
	new snook.player ("Caroline Walch", "", 'ENG'),
	new snook.player ("Charles Jaques", "", 'ENG'),
	new snook.player ("Chris Henry", "", 'ENG'),
	new snook.player ("Chris Norbury", "", 'ENG'),
	new snook.player ("Chris Scanlon", "", 'ENG'),
	new snook.player ("Chris Wakelin", "", 'ENG'),
	new snook.player ("Christopher Keogan", "", 'ENG'),
	new snook.player ("Clive Everton", "", 'ENG'),
	new snook.player ("Colin Morton", "", 'ENG'),
	new snook.player ("Craig Butler", "", 'ENG'),
	new snook.player ("Craig Edwards", "", 'ENG'),
	new snook.player ("Craig Steadman", "", 'ENG'),
	new snook.player ("Daniel Ward", "", 'ENG'),
	new snook.player ("Danny Fowler", "", 'ENG'),
	new snook.player ("Darren Clarke", "", 'ENG'),
	new snook.player ("Darryl Hill", "", 'ENG'),
	new snook.player ("Darryn Walker", "", 'ENG'),
	new snook.player ("Daryl Peach", "", 'ENG'),
	new snook.player ("Dave Chalmers", "", 'ENG'),
	new snook.player ("Dave Gilbert", "", 'ENG'),
	new snook.player ("Dave Harold", "", 'ENG'),
	new snook.player ("Dave Martin", "", 'ENG'),
	new snook.player ("David Finbow", "", 'ENG'),
	new snook.player ("David Gilbert", "", 'ENG'),
	new snook.player ("David Grace", "", 'ENG'),
	new snook.player ("David Gray", "David Gray (snookerzysta)", 'ENG'),
	new snook.player ("David Greaves", "", 'ENG'),
	new snook.player ("David Hall", "", 'ENG'),
	new snook.player ("David Lilley", "", 'ENG'),
	new snook.player ("David Roe", "", 'ENG'),
	new snook.player ("David Taylor", "", 'ENG'),
	new snook.player ("Dean Reynolds", "", 'ENG'),
	new snook.player ("Dennis Hughes", "", 'ENG'),
	new snook.player ("Derek Heaton", "", 'ENG'),
	new snook.player ("Dermot McGlinchey", "", 'ENG'),
	new snook.player ("Dilwyn John", "", 'ENG'),
	new snook.player ("Doug French", "", 'ENG'),
	new snook.player ("Eddie Barker", "", 'ENG'),
	new snook.player ("Eddie Manning", "", 'ENG'),
	new snook.player ("Elliot Slessor", "", 'ENG'),
	new snook.player ("Emma Bonney", "", 'ENG'),
	new snook.player ("Emma Parker", "", 'ENG'),
	new snook.player ("Eric Lawlor", "", 'ENG'),
	new snook.player ("Eva Collins", "", 'ENG'),
	new snook.player ("Eva Palmius", "", 'ENG'),
	new snook.player ("Evelyn Morland-Smith", "", 'ENG'),
	new snook.player ("Frank Callan", "", 'ENG'),
	new snook.player ("Fred Davis", "Fred Davis (snookerzysta)", 'ENG'),
	new snook.player ("Fred Davis", "Fred Davis (snookerzysta)", 'ENG'),
	new snook.player ("Fred Lawrence", "", 'ENG'),
	new snook.player ("Fred Smith", "", 'ENG'),
	new snook.player ("Gary Ponting", "", 'ENG'),
	new snook.player ("Gary Wilkinson", "", 'ENG'),
	new snook.player ("Gary Wilson", "", 'ENG'),
	new snook.player ("Geoff Foulds", "", 'ENG'),
	new snook.player ("Geoff Thompson", "", 'ENG'),
	new snook.player ("George Scott", "", 'ENG'),
	new snook.player ("Graham Cripsey", "", 'ENG'),
	new snook.player ("Graham Miles", "", 'ENG'),
	new snook.player ("Hammad Miah", "", 'ENG'),
	new snook.player ("Hannah Jones", "", 'ENG'),
	new snook.player ("Harvey Chandler", "", 'ENG'),
	new snook.player ("Herbert Holt", "", 'ENG'),
	new snook.player ("Ian Brumby", "", 'ENG'),
	new snook.player ("Ian Burns", "", 'ENG'),
	new snook.player ("Ian Glover", "", 'ENG'),
	new snook.player ("Ian Graham", "", 'ENG'),
	new snook.player ("Ian McCulloch", "", 'ENG'),
	new snook.player ("Ian Sargeant", "", 'ENG'),
	new snook.player ("Ian Williamson", "", 'ENG'),
	new snook.player ("Jack Fitzmaurice", "", 'ENG'),
	new snook.player ("Jack Karnehm", "", 'ENG'),
	new snook.player ("Jack Lisowski", "", 'ENG'),
	new snook.player ("James Cahill", "", 'ENG'),
	new snook.player ("James Leadbetter", "", 'ENG'),
	new snook.player ("James McBain", "", 'ENG'),
	new snook.player ("James Tatton", "", 'ENG'),
	new snook.player ("Jamie Bodle", "", 'ENG'),
	new snook.player ("Jamie Cope", "", 'ENG'),
	new snook.player ("Jamie Curtis-Barrett", "", 'ENG'),
	new snook.player ("Jamie Hunter", "", 'ENG'),
	new snook.player ("Jamie O'Neill", "Jamie O\u2019Neill", 'ENG'),
	new snook.player ("Jamie Wilson", "", 'ENG'),
	new snook.player ("Jamie Woodman", "", 'ENG'),
	new snook.player ("Jason Ferguson", "", 'ENG'),
	new snook.player ("Jason Smith", "", 'ENG'),
	new snook.player ("Jason Weston", "", 'ENG'),
	new snook.player ("Jason Whittaker", "", 'ENG'),
	new snook.player ("Jeff Cundy", "", 'ENG'),
	new snook.player ("Jenson Kendrick", "", 'ENG'),
	new snook.player ("Jim Chambers", "", 'ENG'),
	new snook.player ("Jim Meadowcroft", "", 'ENG'),
	new snook.player ("Jimmy Michie", "", 'ENG'),
	new snook.player ("Jimmy Robertson", "", 'ENG'),
	new snook.player ("Jimmy White", "", 'ENG'),
	new snook.player ("Joe Davis", "", 'ENG'),
	new snook.player ("Joe Davis", "", 'ENG'),
	new snook.player ("Joe Johnson", "Joe Johnson (snookerzysta)", 'ENG'),
	new snook.player ("Joe O'Boye", "", 'ENG'),
	new snook.player ("Joe O\u2019Connor", "", 'ENG'),
	new snook.player ("Joe Perry", "Joe Perry (snookerzysta)", 'ENG'),
	new snook.player ("Joel Walker", "", 'ENG'),
	new snook.player ("John Astley", "", 'ENG'),
	new snook.player ("John Barrie", "", 'ENG'),
	new snook.player ("John Dunning", "", 'ENG'),
	new snook.player ("John Giles", "", 'ENG'),
	new snook.player ("John Hargreaves", "", 'ENG'),
	new snook.player ("John Lardner", "", 'ENG'),
	new snook.player ("John Parrott", "", 'ENG'),
	new snook.player ("John Pulman", "", 'ENG'),
	new snook.player ("John Pulman", "", 'ENG'),
	new snook.player ("John Read", "", 'ENG'),
	new snook.player ("John Spencer", "John Spencer (snookerzysta)", 'ENG'),
	new snook.player ("John Virgo", "", 'ENG'),
	new snook.player ("John Whitty", "", 'ENG'),
	new snook.player ("Johnathan Bagley", "", 'ENG'),
	new snook.player ("Jon Wright", "", 'ENG'),
	new snook.player ("Jonathan Barron", "", 'ENG'),
	new snook.player ("Jonathan Birch", "", 'ENG'),
	new snook.player ("Jordan Brown", "", 'ENG'),
	new snook.player ("Judd Trump", "", 'ENG'),
	new snook.player ("June Banks", "", 'ENG'),
	new snook.player ("Justin Astley", "", 'ENG'),
	new snook.player ("Karl Broughton", "", 'ENG'),
	new snook.player ("Karl Burrows", "", 'ENG'),
	new snook.player ("Karl Payne", "", 'ENG'),
	new snook.player ("Katie Henrick", "", 'ENG'),
	new snook.player ("Kelly Fisher", "", 'ENG'),
	new snook.player ("Kelsall Prince", "", 'ENG'),
	new snook.player ("Ken Owers", "", 'ENG'),
	new snook.player ("Kim Shaw", "", 'ENG'),
	new snook.player ("Kingsley Kennerley", "", 'ENG'),
	new snook.player ("Kuldesh Johal", "", 'ENG'),
	new snook.player ("Kyren Wilson", "", 'ENG'),
	new snook.player ("Lawrie Annandale", "", 'ENG'),
	new snook.player ("Lee Page", "", 'ENG'),
	new snook.player ("Lee Richardson", "", 'ENG'),
	new snook.player ("Lee Spick", "", 'ENG'),
	new snook.player ("Leigh Griffin", "", 'ENG'),
	new snook.player ("Les Dodd", "", 'ENG'),
	new snook.player ("Lewis Roberts", "", 'ENG'),
	new snook.player ("Liam Highfield", "", 'ENG'),
	new snook.player ("Liliya Cerush", "", 'ENG'),
	new snook.player ("Lisa Ingall", "", 'ENG'),
	new snook.player ("Lisa Quick", "", 'ENG'),
	new snook.player ("Louis Heathcote", "", 'ENG'),
	new snook.player ("Luke Fisher", "", 'ENG'),
	new snook.player ("Luke Simmonds", "", 'ENG'),
	new snook.player ("Malcolm Bradley", "", 'ENG'),
	new snook.player ("Mandy Fisher", "", 'ENG'),
	new snook.player ("Marcus Campbell", "", 'ENG'),
	new snook.player ("Margarita Lisovenko", "", 'ENG'),
	new snook.player ("Maria Catalano", "", 'ENG'),
	new snook.player ("Mark Bennett", "", 'ENG'),
	new snook.player ("Mark Davis", "Mark Davis (snookerzysta)", 'ENG'),
	new snook.player ("Mark Flowerdew", "", 'ENG'),
	new snook.player ("Mark Gray", "", 'ENG'),
	new snook.player ("Mark Johnston-Allen", "", 'ENG'),
	new snook.player ("Mark Joyce", "", 'ENG'),
	new snook.player ("Mark King", "Mark King (snookerzysta)", 'ENG'),
	new snook.player ("Mark Rowing", "", 'ENG'),
	new snook.player ("Mark Selby", "", 'ENG'),
	new snook.player ("Mark Wildman", "", 'ENG'),
	new snook.player ("Martin Clark", "", 'ENG'),
	new snook.player ("Martin Gould", "", 'ENG'),
	new snook.player ("Martin O\u2019Donnell", "", 'ENG'),
	new snook.player ("Martin Smith", "", 'ENG'),
	new snook.player ("Matt Wilson", "", 'ENG'),
	new snook.player ("Matthew Couch", "", 'ENG'),
	new snook.player ("Matthew Davies", "", 'ENG'),
	new snook.player ("Matthew Day", "", 'ENG'),
	new snook.player ("Matthew Selt", "", 'ENG'),
	new snook.player ("Matwij Lahodsynskyj", "", 'ENG'),
	new snook.player ("Maureen Baynton", "", 'ENG'),
	new snook.player ("Maurice Parkin", "", 'ENG'),
	new snook.player ("Melbourne Inman", "", 'ENG'),
	new snook.player ("Michael Georgiou", "", 'ENG'),
	new snook.player ("Michael Holt", "Michael Holt (snookerzysta)", 'ENG'),
	new snook.player ("Michael Rhodes", "", 'ENG'),
	new snook.player ("Michael Shelton", "", 'ENG'),
	new snook.player ("Michael Wasley", "", 'ENG'),
	new snook.player ("Michael Wild", "", 'ENG'),
	new snook.player ("Mick Fisher", "", 'ENG'),
	new snook.player ("Mick Price", "", 'ENG'),
	new snook.player ("Mike Darrington", "", 'ENG'),
	new snook.player ("Mike Dunn", "", 'ENG'),
	new snook.player ("Mike Hallett", "", 'ENG'),
	new snook.player ("Mike Watterson", "", 'ENG'),
	new snook.player ("Mitchell Mann", "", 'ENG'),
	new snook.player ("Munraj Pal", "", 'ENG'),
	new snook.player ("Muriel Hazeldene", "", 'ENG'),
	new snook.player ("Nat Butler", "", 'ENG'),
	new snook.player ("Neal Foulds", "", 'ENG'),
	new snook.player ("Neil Mosley", "", 'ENG'),
	new snook.player ("Nick Dyson", "", 'ENG'),
	new snook.player ("Nick Fruin", "", 'ENG'),
	new snook.player ("Nick Marsh", "", 'ENG'),
	new snook.player ("Nick Terry", "", 'ENG'),
	new snook.player ("Nick Walker", "", 'ENG'),
	new snook.player ("Nicolas Pearce", "", 'ENG'),
	new snook.player ("Nigel Bond", "", 'ENG'),
	new snook.player ("Nigel Gilbert", "", 'ENG'),
	new snook.player ("Oliver Brown", "", 'ENG'),
	new snook.player ("Oliver King", "", 'ENG'),
	new snook.player ("Oliver Lines", "", 'ENG'),
	new snook.player ("Pat Houlihan", "", 'ENG'),
	new snook.player ("Pat Kenny", "", 'ENG'),
	new snook.player ("Paul Cavney", "", 'ENG'),
	new snook.player ("Paul Davies", "Paul Davies (snookerzysta)", 'ENG'),
	new snook.player ("Paul Davison", "", 'ENG'),
	new snook.player ("Paul Gibson", "", 'ENG'),
	new snook.player ("Paul Hunter", "", 'ENG'),
	new snook.player ("Paul McPhillips", "", 'ENG'),
	new snook.player ("Paul Medati", "", 'ENG'),
	new snook.player ("Paul Sweeny", "", 'ENG'),
	new snook.player ("Paul Tanner", "", 'ENG'),
	new snook.player ("Paul Wykes", "", 'ENG'),
	new snook.player ("Peter Devlin", "", 'ENG'),
	new snook.player ("Peter Ebdon", "", 'ENG'),
	new snook.player ("Peter Gilchrist", "", 'ENG'),
	new snook.player ("Peter Lines", "", 'ENG'),
	new snook.player ("Peter McCullagh", "", 'ENG'),
	new snook.player ("Ram Vaswani", "", 'ENG'),
	new snook.player ("Ray Edmonds", "", 'ENG'),
	new snook.player ("Reanne Evans", "", 'ENG'),
	new snook.player ("Rebecca Kenna", "", 'ENG'),
	new snook.player ("Rex Williams", "", 'ENG'),
	new snook.player ("Richard Somauroo", "", 'ENG'),
	new snook.player ("Ricky Walden", "", 'ENG'),
	new snook.player ("Riley Parsons", "", 'ENG'),
	new snook.player ("Robbie Williams", "", 'ENG'),
	new snook.player ("Robert Marshall", "", 'ENG'),
	new snook.player ("Robert Milkins", "", 'ENG'),
	new snook.player ("Robert Stephen", "", 'ENG'),
	new snook.player ("Rochelle Woods", "", 'ENG'),
	new snook.player ("Rod Lawler", "", 'ENG'),
	new snook.player ("Roger Baksa", "", 'ENG'),
	new snook.player ("Roger Bales", "", 'ENG'),
	new snook.player ("Roger Garrett", "", 'ENG'),
	new snook.player ("Ron Gross", "", 'ENG'),
	new snook.player ("Ronnie O'Sullivan", "Ronnie O\u2019Sullivan", 'ENG'),
	new snook.player ("Rory McLeod", "", 'ENG'),
	new snook.player ("Ruth Harrison", "", 'ENG'),
	new snook.player ("Ryan Clark", "", 'ENG'),
	new snook.player ("Sam Baird", "", 'ENG'),
	new snook.player ("Sam Craigie", "", 'ENG'),
	new snook.player ("Sanderson Lam", "", 'ENG'),
	new snook.player ("Sean Lanigan", "", 'ENG'),
	new snook.player ("Sean Maddocks", "", 'ENG'),
	new snook.player ("Sean O'Sullivan", "", 'ENG'),
	new snook.player ("Sean Storey", "", 'ENG'),
	new snook.player ("Shailesh Jogia", "", 'ENG'),
	new snook.player ("Shaun Mellish", "", 'ENG'),
	new snook.player ("Shaun Murphy", "", 'ENG'),
	new snook.player ("Sid Hood", "", 'ENG'),
	new snook.player ("Sidney Fry", "", 'ENG'),
	new snook.player ("Sidney Smith", "", 'ENG'),
	new snook.player ("Simon Bedford", "", 'ENG'),
	new snook.player ("Spencer Dunn", "", 'ENG'),
	new snook.player ("Stacey Hillyard", "", 'ENG'),
	new snook.player ("Stan Moody", "", 'ENG'),
	new snook.player ("Stanley Newman", "", 'ENG'),
	new snook.player ("Stephen Craigie", "", 'ENG'),
	new snook.player ("Stephen Kershaw", "", 'ENG'),
	new snook.player ("Stephen Lee", "", 'ENG'),
	new snook.player ("Stephen Rowlings", "", 'ENG'),
	new snook.player ("Steve Campbell", "", 'ENG'),
	new snook.player ("Steve Davis", "", 'ENG'),
	new snook.player ("Steve Duggan", "", 'ENG'),
	new snook.player ("Steve James", "", 'ENG'),
	new snook.player ("Steve Judd", "", 'ENG'),
	new snook.player ("Steve Longworth", "", 'ENG'),
	new snook.player ("Steve Meakin", "", 'ENG'),
	new snook.player ("Steve Newbury", "", 'ENG'),
	new snook.player ("Steve Prest", "", 'ENG'),
	new snook.player ("Steven Hallworth", "", 'ENG'),
	new snook.player ("Stuart Bingham", "", 'ENG'),
	new snook.player ("Stuart Carrington", "", 'ENG'),
	new snook.player ("Stuart Mann", "", 'ENG'),
	new snook.player ("Stuart Pettman", "", 'ENG'),
	new snook.player ("Stuart Reardon", "", 'ENG'),
	new snook.player ("Sue Foster", "", 'ENG'),
	new snook.player ("Sunit Vaswani", "", 'ENG'),
	new snook.player ("Surinder Gill", "", 'ENG'),
	new snook.player ("Suzie Opacic", "", 'ENG'),
	new snook.player ("Syd Wilson", "", 'ENG'),
	new snook.player ("Sydney Lee", "", 'ENG'),
	new snook.player ("Sydney Wilson", "", 'ENG'),
	new snook.player ("Terry Griffiths", "", 'ENG'),
	new snook.player ("Terry Murphy", "", 'ENG'),
	new snook.player ("Terry Whitthread", "", 'ENG'),
	new snook.player ("Thelma Carpenter", "", 'ENG'),
	new snook.player ("Tim Bailey", "", 'ENG'),
	new snook.player ("Tom Dennis", "", 'ENG'),
	new snook.player ("Tom Ford", "Tom Ford (snookerzysta)", 'ENG'),
	new snook.player ("Tom Newman", "", 'ENG'),
	new snook.player ("Tom Reece", "", 'ENG'),
	new snook.player ("Tony Chappel", "", 'ENG'),
	new snook.player ("Tony Jones", "", 'ENG'),
	new snook.player ("Tony Knowles", "", 'ENG'),
	new snook.player ("Tony Meo", "", 'ENG'),
	new snook.player ("Troy Shaw", "", 'ENG'),
	new snook.player ("Vera Selby", "", 'ENG'),
	new snook.player ("Vic Harris", "", 'ENG'),
	new snook.player ("Wayne Brown", "", 'ENG'),
	new snook.player ("Wayne Cooper", "", 'ENG'),
	new snook.player ("Willie Smith", "", 'ENG'),
	new snook.player ("Willie Thorne", "", 'ENG'),
	new snook.player ("Zak Surety", "", 'ENG'),

	new snook.player ("Andrejs Pripjoks", "", 'LVA'),
	new snook.player ("Rodion Judin", "", 'LVA'),
	new snook.player ("Tatjana Vasiljeva", "", 'LVA'),

	new snook.player ("Anton Kazakov", "", 'UKR'),
	new snook.player ("Iulian Boiko", "", 'UKR'),
	new snook.player ("Tetiana Vekker", "", 'UKR'),

	new snook.player ("Michelle Marinova", "", 'BGR'),

	new snook.player ("Alan Burnett", "", 'SCO'),
	new snook.player ("Alan McManus", "", 'SCO'),
	new snook.player ("Anthony McGill", "", 'SCO'),
	new snook.player ("Bert Demarco", "", 'SCO'),
	new snook.player ("Billy Snaddon", "", 'SCO'),
	new snook.player ("Chris Ross", "", 'SCO'),
	new snook.player ("Chris Small", "", 'SCO'),
	new snook.player ("Chris Totten", "", 'SCO'),
	new snook.player ("Craig McGillivray", "", 'SCO'),
	new snook.player ("David McLellan", "", 'SCO'),
	new snook.player ("David Sneddon", "", 'SCO'),
	new snook.player ("Dean Young", "", 'SCO'),
	new snook.player ("Drew Henry", "", 'SCO'),
	new snook.player ("Duncan Campbell", "", 'SCO'),
	new snook.player ("Eddie McLaughlin", "", 'SCO'),
	new snook.player ("Eddie Sinclair", "", 'SCO'),
	new snook.player ("Eden Sharav", "", 'SCO'),
	new snook.player ("Euan Henderson", "", 'SCO'),
	new snook.player ("Fraser Patrick", "", 'SCO'),
	new snook.player ("Gary Thomson", "", 'SCO'),
	new snook.player ("Graeme Dott", "", 'SCO'),
	new snook.player ("Graham Horne", "", 'SCO'),
	new snook.player ("Harry Stokes", "", 'SCO'),
	new snook.player ("Hugh Abernethy", "", 'SCO'),
	new snook.player ("Ian Black", "", 'SCO'),
	new snook.player ("James McBain", "", 'SCO'),
	new snook.player ("Jamie Burnett", "", 'SCO'),
	new snook.player ("Jim Donnelly", "", 'SCO'),
	new snook.player ("John Higgins", "", 'SCO'),
	new snook.player ("John Lardner", "", 'SCO'),
	new snook.player ("John Phillips", "", 'SCO'),
	new snook.player ("John Rea", "", 'SCO'),
	new snook.player ("Liam Graham", "", 'SCO'),
	new snook.player ("Marcus Campbell", "", 'SCO'),
	new snook.player ("Margaret Lennan", "", 'SCO'),
	new snook.player ("Mark Boyle", "", 'SCO'),
	new snook.player ("Martin Dziewialtowski", "", 'SCO'),
	new snook.player ("Matt Gibson", "", 'SCO'),
	new snook.player ("Michael Collumb", "", 'SCO'),
	new snook.player ("Michael Leslie", "", 'SCO'),
	new snook.player ("Michael Maguire", "", 'SCO'),
	new snook.player ("Murdo MacLeod", "", 'SCO'),
	new snook.player ("Paul McPhillips", "", 'SCO'),
	new snook.player ("Rhys Clark", "", 'SCO'),
	new snook.player ("Robert Carlisle", "", 'SCO'),
	new snook.player ("Robert Shanks", "", 'SCO'),
	new snook.player ("Robert Stephen", "", 'SCO'),
	new snook.player ("Ross Muir", "", 'SCO'),
	new snook.player ("Scott Donaldson", "", 'SCO'),
	new snook.player ("Scott MacKenzie", "", 'SCO'),
	new snook.player ("Stephen Hendry", "", 'SCO'),
	new snook.player ("Stephen Maguire", "", 'SCO'),
	new snook.player ("Steven Bennie", "", 'SCO'),
	new snook.player ("Walter Donaldson", "Walter Donaldson (snookerzysta)", 'SCO'),

	new snook.player ("Mehmet Husnu", "", 'CYP'),
	new snook.player ("Michael Georgiou", "", 'CYP'),

	new snook.player ("Alex Borg", "", 'MLT'),
	new snook.player ("Brian Cini", "", 'MLT'),
	new snook.player ("Duncan Bezzina", "", 'MLT'),
	new snook.player ("Joe Grech", "", 'MLT'),
	new snook.player ("Paul Mifsud", "", 'MLT'),
	new snook.player ("Simon Zammit", "", 'MLT'),
	new snook.player ("Tony Drago", "", 'MLT'),
	new snook.player ("Wilfred Asciak", "", 'MLT'),

	new snook.player ("Agnes Davies", "", 'WAL'),
	new snook.player ("Alwyn Lloyd", "", 'WAL'),
	new snook.player ("Andrew Pagett", "", 'WAL'),
	new snook.player ("Anthony Davies", "", 'WAL'),
	new snook.player ("Ben Jones", "", 'WAL'),
	new snook.player ("Cliff Wilson", "", 'WAL'),
	new snook.player ("Clive Everton", "", 'WAL'),
	new snook.player ("Colin Roscoe", "", 'WAL'),
	new snook.player ("Daniel Wells", "", 'WAL'),
	new snook.player ("Darren Morgan", "", 'WAL'),
	new snook.player ("David John", "", 'WAL'),
	new snook.player ("Dominic Dale", "", 'WAL'),
	new snook.player ("Doug Mountjoy", "", 'WAL'),
	new snook.player ("Duane Jones", "", 'WAL'),
	new snook.player ("Dylan Emery", "", 'WAL'),
	new snook.player ("Eirian Williams", "", 'WAL'),
	new snook.player ("Gareth Allen", "", 'WAL'),
	new snook.player ("Gareth Coppack", "", 'WAL'),
	new snook.player ("Gary Owen", "", 'WAL'),
	new snook.player ("Geoff Thomas", "", 'WAL'),
	new snook.player ("Gwyn Evans", "", 'WAL'),
	new snook.player ("Ian Preece", "", 'WAL'),
	new snook.player ("Jackson Page", "", 'WAL'),
	new snook.player ("Jak Jones", "", 'WAL'),
	new snook.player ("Jamie Clarke", "", 'WAL'),
	new snook.player ("Jamie Jones", "", 'WAL'),
	new snook.player ("Kishan Hirani", "", 'WAL'),
	new snook.player ("Laura Evans", "", 'WAL'),
	new snook.player ("Lee Walker", "", 'WAL'),
	new snook.player ("Marcus Owen", "", 'WAL'),
	new snook.player ("Mark Bennett", "", 'WAL'),
	new snook.player ("Mark Fenton", "", 'WAL'),
	new snook.player ("Mark J. Williams", "", 'WAL'),
	new snook.player ("Matthew Stevens", "", 'WAL'),
	new snook.player ("Michael White", "Michael White (snookerzysta)", 'WAL'),
	new snook.player ("Paul Davies", "Paul Davies (snookerzysta)", 'WAL'),
	new snook.player ("Philip Williams", "", 'WAL'),
	new snook.player ("Ray Reardon", "", 'WAL'),
	new snook.player ("Rhydian Richards", "", 'WAL'),
	new snook.player ("Ron Jones", "", 'WAL'),
	new snook.player ("Roy Andrewartha", "", 'WAL'),
	new snook.player ("Ryan Day", "", 'WAL'),
	new snook.player ("Steve Newbury", "", 'WAL'),
	new snook.player ("Terry Griffiths", "", 'WAL'),
	new snook.player ("Terry Parsons", "", 'WAL'),
	new snook.player ("Tom Carpenter", "", 'WAL'),
	new snook.player ("Tony Chappel", "", 'WAL'),
	new snook.player ("Tyler Rees", "", 'WAL'),
	new snook.player ("Wayne Jones", "", 'WAL'),

	new snook.player ("Derek Mienie", "", 'ZAF'),
	new snook.player ("Fran\u00e7ois Ellis", "", 'ZAF'),
	new snook.player ("Fred Van Rensburg", "", 'ZAF'),
	new snook.player ("Jimmy van Rensberg", "", 'ZAF'),
	new snook.player ("Manuel Francisco", "", 'ZAF'),
	new snook.player ("Mike Hines", "", 'ZAF'),
	new snook.player ("Perrie Mans", "", 'ZAF'),
	new snook.player ("Peter Francisco", "", 'ZAF'),
	new snook.player ("Robbie Grace", "", 'ZAF'),
	new snook.player ("Roy Amdor", "", 'ZAF'),
	new snook.player ("Silvino Francisco", "", 'ZAF'),

	new snook.player ("Alex Higgins", "", 'NIR'),
	new snook.player ("Declan Hughes", "", 'NIR'),
	new snook.player ("Dennis Taylor", "Dennis Taylor (snookerzysta)", 'NIR'),
	new snook.player ("Dermot McGlinchey", "", 'NIR'),
	new snook.player ("Gerard Greene", "", 'NIR'),
	new snook.player ("Jack McLaughlin", "", 'NIR'),
	new snook.player ("Jackie Rea", "", 'NIR'),
	new snook.player ("Jason Prince", "", 'NIR'),
	new snook.player ("Joe Meara", "", 'NIR'),
	new snook.player ("Joe Swail", "", 'NIR'),
	new snook.player ("Jordan Brown", "", 'NIR'),
	new snook.player ("Karen Corr", "", 'NIR'),
	new snook.player ("Mark Allen", "Mark Allen (snookerzysta)", 'NIR'),
	new snook.player ("Patrick Wallace", "", 'NIR'),
	new snook.player ("Robbie McGuigan", "", 'NIR'),
	new snook.player ("Sean O'Neill", "", 'NIR'),
	new snook.player ("Tommy Murphy", "", 'NIR'),

	new snook.player ("Aaron Hill", "", 'IRL'),
	new snook.player ("Billy Kelly", "", 'IRL'),
	new snook.player ("Brendan O'Donoghue", "", 'IRL'),
	new snook.player ("Colm Gilcreest", "", 'IRL'),
	new snook.player ("David (Dave) McDonnell", "", 'IRL'),
	new snook.player ("David Hogan", "", 'IRL'),
	new snook.player ("David Morris", "David Morris (snookerzysta)", 'IRL'),
	new snook.player ("Dessie Sheehan", "", 'IRL'),
	new snook.player ("Eugene Hughes", "", 'IRL'),
	new snook.player ("Fergal O'Brien", "Fergal O\u2019Brien", 'IRL'),
	new snook.player ("Greg Casey", "", 'IRL'),
	new snook.player ("Jason Devaney", "", 'IRL'),
	new snook.player ("Joe Brady", "", 'IRL'),
	new snook.player ("Joe Delaney", "", 'IRL'),
	new snook.player ("Joe O'Boye", "", 'IRL'),
	new snook.player ("Josh Boileau", "", 'IRL'),
	new snook.player ("Ken Doherty", "Ken Doherty (snookerzysta)", 'IRL'),
	new snook.player ("Leo Fernandez", "", 'IRL'),
	new snook.player ("Martin McCrudden", "", 'IRL'),
	new snook.player ("Michael Judge", "", 'IRL'),
	new snook.player ("Paddy Browne", "", 'IRL'),
	new snook.player ("Pascal Burke", "", 'IRL'),
	new snook.player ("Patsy Fagan", "", 'IRL'),
	new snook.player ("Paul Watchorn", "", 'IRL'),
	new snook.player ("Robert Murphy", "", 'IRL'),
	new snook.player ("Rodney Goggins", "", 'IRL'),
	new snook.player ("Ross Bulman", "", 'IRL'),
	new snook.player ("Stephen Murphy", "", 'IRL'),
	new snook.player ("Stephen O'Connor", "", 'IRL'),
	new snook.player ("TJ Dowling", "", 'IRL'),
	new snook.player ("Tony Kearney", "", 'IRL'),
	new snook.player ("Vincent Muldoon", "", 'IRL'),

	new snook.player ("Bulcs\u00fa R\u00e9v\u00e9sz", "", 'HUN'),

	new snook.player ("Oscar Medela", "", 'ESP'),

	new snook.player ("Gerrit bij de Leij", "", 'NLD'),
	new snook.player ("Mario Wehrmann", "", 'NLD'),
	new snook.player ("Rolf de Jong", "", 'NLD'),
	new snook.player ("Roy Stolk", "", 'NLD'),
	new snook.player ("Stefan Mazrocis", "", 'NLD'),

	new snook.player ("Ahmed Aly", "", 'USA'),
	new snook.player ("Harry Lukens", "", 'USA'),
	new snook.player ("Jim Rempe", "", 'USA'),
	new snook.player ("Paul Kimura", "", 'USA'),
	new snook.player ("Raymond Fung", "", 'USA'),
	new snook.player ("Steve Mizerak", "", 'USA'),
	new snook.player ("Tom Kollins", "", 'USA'),

	new snook.player ("Ben Mertens", "", 'BEL'),
	new snook.player ("Bjorn Haneveer", "", 'BEL'),
	new snook.player ("Chris Henry", "", 'BEL'),
	new snook.player ("Daan Leyssen", "", 'BEL'),
	new snook.player ("Danny Lathouwers", "", 'BEL'),
	new snook.player ("Jeff Jacobs", "", 'BEL'),
	new snook.player ("Johan van Goetham", "", 'BEL'),
	new snook.player ("Julien Leclercq", "", 'BEL'),
	new snook.player ("Kevin Hanssens", "", 'BEL'),
	new snook.player ("Kevin Van Hove-Speltincx", "", 'BEL'),
	new snook.player ("Luca Brecel", "", 'BEL'),
	new snook.player ("Mario Geudens", "", 'BEL'),
	new snook.player ("Patrick Delsemme", "", 'BEL'),
	new snook.player ("Peter Bullen", "", 'BEL'),
	new snook.player ("Stefan Van Der Borght", "", 'BEL'),
	new snook.player ("Steve Lemmens", "", 'BEL'),
	new snook.player ("Tomasz Skalski", "", 'BEL'),
	new snook.player ("Yvan Van Velthoven", "", 'BEL'),

	new snook.player ("Heikki Niva", "", 'FIN'),
	new snook.player ("Jyri Virtanen", "", 'FIN'),
	new snook.player ("Mika Karhu", "", 'FIN'),
	new snook.player ("Robin Hull", "", 'FIN'),

	new snook.player ("Chan Keng Kwang", "", 'SGP'),
	new snook.player ("Peter Gilchrist", "", 'SGP'),

	new snook.player ("Ann Sofie L\u00f6fgren", "", 'SWE'),
	new snook.player ("Monika Margeta", "", 'SWE'),

	new snook.player ("Michael Patrick Seiter", "", 'LIE'),

	new snook.player ("Daniel Kandi", "", 'DNK'),
	new snook.player ("Rune Kampe", "", 'DNK'),

	new snook.player ("Adam Stefanow", "Adam Stefan\u00f3w", 'POL'),
	new snook.player ("Antoni Kowalski", "Antoni Kowalski (snookerzysta)", 'POL'),
	new snook.player ("Bogdan Wo\u0142kowski", "", 'POL'),
	new snook.player ("Hanna Mergies", "", 'POL'),
	new snook.player ("Jaros\u0142aw Kowalski", "", 'POL'),
	new snook.player ("Kacper Filipiak", "", 'POL'),
	new snook.player ("Krzysztof Wr\u00f3bel", "", 'POL'),
	new snook.player ("Kuba Sawicki", "", 'POL'),
	new snook.player ("Marcin Nitschke", "", 'POL'),
	new snook.player ("Marek Derek", "", 'POL'),
	new snook.player ("Marek Zubrzycki", "", 'POL'),
	new snook.player ("Mariusz Sirko", "", 'POL'),
	new snook.player ("Mateusz Baranowski", "", 'POL'),
	new snook.player ("Micha\u0142 Zieli\u0144ski", "Micha\u0142 Zieli\u0144ski (snookerzysta)", 'POL'),
	new snook.player ("Przemys\u0142aw Kruk", "", 'POL'),
	new snook.player ("Rafa\u0142 G\u00f3recki", "", 'POL'),
	new snook.player ("Rafa\u0142 Jewtuch", "", 'POL'),

	new snook.player ("Simona Mili\u0161auskait\u0117", "", 'LTU'),

	new snook.player ("Alexander Ursenbacher", "", 'CHE'),
	new snook.player ("Luis Vetter", "", 'CHE'),
	new snook.player ("Regula Hitz", "", 'CHE'),

	new snook.player ("Habib Subah", "", 'BHR'),

	new snook.player ("Andreas Ploner", "", 'AUT'),
	new snook.player ("Florian N\u00fc\u00dfle", "", 'AUT'),

	new snook.player ("Adrian Ridley", "", 'AUS'),
	new snook.player ("Alan McDonald", "", 'AUS'),
	new snook.player ("Anna Lynch", "", 'AUS'),
	new snook.player ("Ben Judge", "", 'AUS'),
	new snook.player ("Bob Marshall", "", 'AUS'),
	new snook.player ("Cliff Rickard", "", 'AUS'),
	new snook.player ("Eddie Charlton", "", 'AUS'),
	new snook.player ("Gary Owen", "", 'AUS'),
	new snook.player ("Glen Wilkinson", "", 'AUS'),
	new snook.player ("Greg Jenkins", "", 'AUS'),
	new snook.player ("Horace Lindrum", "", 'AUS'),
	new snook.player ("Ian Anderson", "", 'AUS'),
	new snook.player ("James Giannaros", "", 'AUS'),
	new snook.player ("Jessica Woods", "", 'AUS'),
	new snook.player ("Johl Younger", "", 'AUS'),
	new snook.player ("John Campbell", "", 'AUS'),
	new snook.player ("Kathy Parashis", "", 'AUS'),
	new snook.player ("Kurt Dunham", "", 'AUS'),
	new snook.player ("Leon Heywood", "", 'AUS'),
	new snook.player ("Lesley McIlrath", "", 'AUS'),
	new snook.player ("Lou Condo", "", 'AUS'),
	new snook.player ("Matthew Bolton", "", 'AUS'),
	new snook.player ("Michael Quinn", "", 'AUS'),
	new snook.player ("Neil Robertson", "", 'AUS'),
	new snook.player ("Paddy Morgan", "", 'AUS'),
	new snook.player ("Philip Tarrant", "", 'AUS'),
	new snook.player ("Rex King", "", 'AUS'),
	new snook.player ("Robby Foldvari", "", 'AUS'),
	new snook.player ("Ryan Thomerson", "", 'AUS'),
	new snook.player ("Sam Frangie", "", 'AUS'),
	new snook.player ("Steve Mifsud", "", 'AUS'),
	new snook.player ("Vinnie Calabrese", "", 'AUS'),
	new snook.player ("Vladimir Potazsnyk", "", 'AUS'),
	new snook.player ("Warren King", "", 'AUS'),
	new snook.player ("Warren Simpson", "", 'AUS'),

	new snook.player ("Chris McBreen", "", 'NZL'),
	new snook.player ("Clark McConachy", "", 'NZL'),
	new snook.player ("Dene O'Kane", "", 'NZL'),
	new snook.player ("Edward James O'Donoghue", "", 'NZL'),
	new snook.player ("Norman Powell Squire", "", 'NZL'),

	new snook.player ("Aditya Mehta", "", 'IND'),
	new snook.player ("Alok Kumar", "", 'IND'),
	new snook.player ("Amee Kamani", "", 'IND'),
	new snook.player ("Amrik Cheema", "", 'IND'),
	new snook.player ("Anuja Thakur", "", 'IND'),
	new snook.player ("Arantxa Sanchis", "", 'IND'),
	new snook.player ("Arvind Savur", "", 'IND'),
	new snook.player ("Brijesh Damani", "", 'IND'),
	new snook.player ("Chandra Hirjee", "", 'IND'),
	new snook.player ("Chitra Magimairaj", "", 'IND'),
	new snook.player ("Geet Sethi", "", 'IND'),
	new snook.player ("Himanshu Dinesh Jain", "", 'IND'),
	new snook.player ("Lucky Vatnani", "", 'IND'),
	new snook.player ("Manan Chandra", "", 'IND'),
	new snook.player ("Omprakesh Agrawal", "", 'IND'),
	new snook.player ("Pankaj Advani", "", 'IND'),
	new snook.player ("R Umadevi Nagaraj", "", 'IND'),
	new snook.player ("Subhash Agarwal", "", 'IND'),
	new snook.player ("Vidya Pillai", "", 'IND'),
	new snook.player ("Yasin Merchant", "", 'IND'),

	new snook.player ("Rory McLeod", "", 'JAM'),

	new snook.player ("Aaron Canavan", "", 'JEY'),

	new snook.player ("Basem Eltahhan", "", 'EGY'),
	new snook.player ("Hatem Yassen", "", 'EGY'),
	new snook.player ("Mohamed Ibrahim", "", 'EGY'),
	new snook.player ("Mohamed Khairy", "", 'EGY'),
	new snook.player ("Wael Talaat", "", 'EGY'),
	new snook.player ("Yara Sharafeldin", "", 'EGY'),

	new snook.player ("Amir Sarkhosh", "", 'IRN'),
	new snook.player ("Hossein Vafaei", "", 'IRN'),
	new snook.player ("Soheil Vahedi", "", 'IRN'),

	new snook.player ("Eden Sharav", "", 'ISR'),
	new snook.player ("Roey Fernandez", "", 'ISR'),
	new snook.player ("Shachar Ruberg", "", 'ISR'),

	new snook.player ("Moh Keen Hoo", "", 'MYS'),
	new snook.player ("Sam Chong", "", 'MYS'),
	new snook.player ("Thor Chuan Leong", "", 'MYS'),

	new snook.player ("Ahsan Ramzan", "", 'PAK'),
	new snook.player ("Asjaq Iqbal", "", 'PAK'),
	new snook.player ("Babar Masih", "", 'PAK'),
	new snook.player ("Farakh Ajaib", "", 'PAK'),
	new snook.player ("Farhan Mirza", "", 'PAK'),
	new snook.player ("Hamza Akbar", "", 'PAK'),
	new snook.player ("Khurram Hussain Agha", "", 'PAK'),
	new snook.player ("Muhammad Asif", "", 'PAK'),
	new snook.player ("Muhammad Sajjad", "", 'PAK'),
	new snook.player ("Muhammad Yousaf", "", 'PAK'),
	new snook.player ("Naveen Perwani", "", 'PAK'),
	new snook.player ("Shokat Ali", "", 'PAK'),

	new snook.player ("Ahmed Saif", "", 'QAT'),

	new snook.player ("Andy Lee", "", 'HKG'),
	new snook.player ("Au Chi-wai", "", 'HKG'),
	new snook.player ("Chan Wai Ki", "", 'HKG'),
	new snook.player ("Chan Wok Ming", "", 'HKG'),
	new snook.player ("Franky Chan", "", 'HKG'),
	new snook.player ("Fung Kwok Wai", "", 'HKG'),
	new snook.player ("Jaique Ip", "", 'HKG'),
	new snook.player ("Ka Wai Cheung", "", 'HKG'),
	new snook.player ("Katrina Wan", "", 'HKG'),
	new snook.player ("Kenny Kwok", "", 'HKG'),
	new snook.player ("Marco Fu", "", 'HKG'),
	new snook.player ("Mini Chu", "", 'HKG'),
	new snook.player ("Ng On Yee", "", 'HKG'),

	new snook.player ("Wu Yu Lin", "", 'TWN'),

	new snook.player ("Akani Songsermsawad", "", 'THA'),
	new snook.player ("Atthasit Mahitthi", "", 'THA'),
	new snook.player ("Boonyarit Keattikun", "", 'THA'),
	new snook.player ("Dechawat Poomjaeng", "", 'THA'),
	new snook.player ("Issara Kachaiwong", "", 'THA'),
	new snook.player ("James Wattana", "", 'THA'),
	new snook.player ("Kobkit Palajin", "", 'THA'),
	new snook.player ("Kritsanut Lertsattayathorn", "", 'THA'),
	new snook.player ("Kwan Poomjang", "", 'THA'),
	new snook.player ("Noppadol Sangnil", "", 'THA'),
	new snook.player ("Noppadon Noppachorn", "", 'THA'),
	new snook.player ("Noppon Saengkham", "", 'THA'),
	new snook.player ("Nutcharut Wongharuthai", "", 'THA'),
	new snook.player ("Passakorn Suwannawat", "", 'THA'),
	new snook.player ("Phaitoon Phonbun", "", 'THA'),
	new snook.player ("Ratchayothin Yotharuck", "", 'THA'),
	new snook.player ("Rom Surin", "", 'THA'),
	new snook.player ("Sakchai Sim Ngam", "", 'THA'),
	new snook.player ("Siripaporn Nuanthakhamjan", "", 'THA'),
	new snook.player ("Supoj Saenla", "", 'THA'),
	new snook.player ("Tai Pichit", "", 'THA'),
	new snook.player ("Thanawat Thirapongpaiboon", "", 'THA'),
	new snook.player ("Thepchaiya Un-Nooh", "", 'THA'),
	new snook.player ("Waratthanun Sukritthanes", "", 'THA'),

	new snook.player ("Mohammed Shehab", "", 'ARE'),
	new snook.player ("Mohammed al-Joker", "", 'ARE'),

	new snook.player ("Saleh Mohammad", "", 'AFG'),

	new snook.player ("Alex Pagulayan", "", 'PHL'),

	new snook.player ("Darryl Hill", "", 'IMN'),
	new snook.player ("Tony Wilson", "", 'IMN')
];