snook.players = [
	new snook.player ("Yan Bingtao", "", 'CHN'),

	new snook.player ("Adam Duffy", "", 'ENG'),
	new snook.player ("Alfred Burden", "Alfie Burden", 'ENG'),
	new snook.player ("Ali Carter", "Allister Carter", 'ENG'),
	new snook.player ("Andrew Higginson", "", 'ENG'),
	new snook.player ("Andy Hicks", "", 'ENG'),
	new snook.player ("Anthony Hamilton", "Anthony Hamilton (snookerzysta)", 'ENG'),
	new snook.player ("Barry Hawkins", "", 'ENG'),
	new snook.player ("Barry Pinches", "", 'ENG'),
	new snook.player ("Ben Woollaston", "", 'ENG'),
	new snook.player ("Craig Steadman", "", 'ENG'),
	new snook.player ("Dave Harold", "", 'ENG'),
	new snook.player ("David Gilbert", "", 'ENG'),
	new snook.player ("David Grace", "", 'ENG'),
	new snook.player ("David Roe", "", 'ENG'),
	new snook.player ("Fred Davis", "Fred Davis (snookerzysta)", 'ENG'),
	new snook.player ("Fred Lawrence", "", 'ENG'),
	new snook.player ("Gary Wilson", "", 'ENG'),
	new snook.player ("Ian McCulloch", "", 'ENG'),
	new snook.player ("Jack Lisowski", "", 'ENG'),
	new snook.player ("Jamie Cope", "", 'ENG'),
	new snook.player ("Jamie O'Neill", "Jamie O\u2019Neill", 'ENG'),
	new snook.player ("Jimmy Michie", "", 'ENG'),
	new snook.player ("Jimmy Robertson", "", 'ENG'),
	new snook.player ("Jimmy White", "", 'ENG'),
	new snook.player ("Joe Davis", "", 'ENG'),
	new snook.player ("Joe O'Connor", "Joe O\u2019Connor", 'ENG'),
	new snook.player ("Joe Perry", "Joe Perry (snookerzysta)", 'ENG'),
	new snook.player ("John Parrott", "", 'ENG'),
	new snook.player ("John Pulman", "", 'ENG'),
	new snook.player ("John Spencer", "John Spencer (snookerzysta)", 'ENG'),
	new snook.player ("Judd Trump", "", 'ENG'),
	new snook.player ("Kuldesh Johal", "", 'ENG'),
	new snook.player ("Kyren Wilson", "", 'ENG'),
	new snook.player ("Liam Highfield", "", 'ENG'),
	new snook.player ("Mark Davis", "Mark Davis (snookerzysta)", 'ENG'),
	new snook.player ("Mark Joyce", "", 'ENG'),
	new snook.player ("Mark King", "Mark King (snookerzysta)", 'ENG'),
	new snook.player ("Mark Selby", "", 'ENG'),
	new snook.player ("Martin Gould", "", 'ENG'),
	new snook.player ("Martin O'Donnell", "Martin O\u2019Donnell", 'ENG'),
	new snook.player ("Matthew Selt", "", 'ENG'),
	new snook.player ("Michael Holt", "Michael Holt (snookerzysta)", 'ENG'),
	new snook.player ("Michalis Georgiou", "Michael Georgiou", 'ENG'),
	new snook.player ("Mike Dunn", "", 'ENG'),
	new snook.player ("Mike Hallett", "", 'ENG'),
	new snook.player ("Nigel Bond", "", 'ENG'),
	new snook.player ("Paul Davison", "", 'ENG'),
	new snook.player ("Paul Hunter", "", 'ENG'),
	new snook.player ("Peter Ebdon", "", 'ENG'),
	new snook.player ("Peter Lines", "", 'ENG'),
	new snook.player ("Reanne Evans", "", 'ENG'),
	new snook.player ("Ricky Walden", "", 'ENG'),
	new snook.player ("Robert Milkins", "", 'ENG'),
	new snook.player ("Rod Lawler", "", 'ENG'),
	new snook.player ("Ronnie O'Sullivan", "Ronnie O\u2019Sullivan", 'ENG'),
	new snook.player ("Rory McLeod", "", 'ENG'),
	new snook.player ("Sam Baird", "", 'ENG'),
	new snook.player ("Shaun Murphy", "", 'ENG'),
	new snook.player ("Simon Bedford", "", 'ENG'),
	new snook.player ("Stephen Lee", "", 'ENG'),
	new snook.player ("Stephen Rowlings", "", 'ENG'),
	new snook.player ("Steve Davis", "", 'ENG'),
	new snook.player ("Stuart Bingham", "", 'ENG'),
	new snook.player ("Tom Dennis", "", 'ENG'),
	new snook.player ("Tom Ford", "Tom Ford (snookerzysta)", 'ENG'),
	new snook.player ("Tom Newman", "", 'ENG'),
	new snook.player ("Wayne Cooper", "", 'ENG'),
	new snook.player ("Willie Thorne", "", 'ENG'),

	new snook.player ("Alan McManus", "", 'SCO'),
	new snook.player ("Anthony McGill", "", 'SCO'),
	new snook.player ("Chris Small", "", 'SCO'),
	new snook.player ("Drew Henry", "", 'SCO'),
	new snook.player ("Euan Henderson", "", 'SCO'),
	new snook.player ("Graeme Dott", "", 'SCO'),
	new snook.player ("James McBain", "", 'SCO'),
	new snook.player ("Jamie Burnett", "", 'SCO'),
	new snook.player ("John Higgins", "", 'SCO'),
	new snook.player ("Marcus Campbell", "", 'SCO'),
	new snook.player ("Scott Donaldson", "", 'SCO'),
	new snook.player ("Scott MacKenzie", "", 'SCO'),
	new snook.player ("Stephen Hendry", "", 'SCO'),
	new snook.player ("Walter Donaldson", "Walter Donaldson (snookerzysta)", 'SCO'),

	new snook.player ("Michalis Georgiou", "Michael Georgiou", 'CYP'),

	new snook.player ("Andrew Pagett", "", 'WAL'),
	new snook.player ("Daniel Wells", "", 'WAL'),
	new snook.player ("Darren Morgan", "", 'WAL'),
	new snook.player ("Dominic Dale", "", 'WAL'),
	new snook.player ("Doug Mountjoy", "", 'WAL'),
	new snook.player ("Eirian Williams", "", 'WAL'),
	new snook.player ("Gary Owen", "", 'WAL'),
	new snook.player ("Jak Jones", "", 'WAL'),
	new snook.player ("Jamie Jones", "", 'WAL'),
	new snook.player ("Lee Walker", "", 'WAL'),
	new snook.player ("Mark Williams", "Mark J. Williams", 'WAL'),
	new snook.player ("Matthew Stevens", "", 'WAL'),
	new snook.player ("Michael White", "Michael White (snookerzysta)", 'WAL'),
	new snook.player ("Paul Davies", "Paul Davies (snookerzysta)", 'WAL'),
	new snook.player ("Ray Reardon", "", 'WAL'),
	new snook.player ("Ryan Day", "", 'WAL'),
	new snook.player ("Terry Griffiths", "", 'WAL'),
	new snook.player ("Tony Chappel", "", 'WAL'),

	new snook.player ("Alex Higgins", "", 'NIR'),
	new snook.player ("Declan Hughes", "", 'NIR'),
	new snook.player ("Dermot McGlinchey", "", 'NIR'),
	new snook.player ("Gerard Greene", "", 'NIR'),
	new snook.player ("Joe Swail", "", 'NIR'),
	new snook.player ("Jordan Brown", "", 'NIR'),
	new snook.player ("Mark Allen", "Mark Allen (snookerzysta)", 'NIR'),

	new snook.player ("Robin Hull", "", 'FIN'),

	new snook.player ("Gary Owen", "", 'AUS'),

	new snook.player ("Aditya Mehta", "", 'IND'),

	new snook.player ("Rory McLeod", "", 'JAM'),

	new snook.player ("Marco Fu", "", 'HKG')
];