snook.players = [
	new snook.player ("Brian Ochoiski", "", 'FRA'),

	new snook.player ("He Guoqiang", "", 'CHN'),
	new snook.player ("Yan Bingtao", "", 'CHN'),

	new snook.player ("Christopher Watts", "", 'NOR'),

	new snook.player ("Adam Davies", "", 'ENG'),
	new snook.player ("Adam Duffy", "", 'ENG'),
	new snook.player ("Adrian Rosa", "", 'ENG'),
	new snook.player ("Albert Brown", "", 'ENG'),
	new snook.player ("Albert Cope", "", 'ENG'),
	new snook.player ("Alec Mann", "", 'ENG'),
	new snook.player ("Alex Davies", "", 'ENG'),
	new snook.player ("Alfred Burden", "Alfie Burden", 'ENG'),
	new snook.player ("Ali Carter", "Allister Carter", 'ENG'),
	new snook.player ("Allan Taylor", "", 'ENG'),
	new snook.player ("Andrew Cairns", "", 'ENG'),
	new snook.player ("Andrew Higginson", "", 'ENG'),
	new snook.player ("Andy Hicks", "", 'ENG'),
	new snook.player ("Andy Lee", "", 'ENG'),
	new snook.player ("Ann-Marie Farren", "", 'ENG'),
	new snook.player ("Anthony Hamilton", "Anthony Hamilton (snookerzysta)", 'ENG'),
	new snook.player ("Anthony Harris", "", 'ENG'),
	new snook.player ("Ashley Carty", "", 'ENG'),
	new snook.player ("Ashley Hugill", "", 'ENG'),
	new snook.player ("Ashley Wright", "", 'ENG'),
	new snook.player ("Barry Hawkins", "", 'ENG'),
	new snook.player ("Barry Pinches", "", 'ENG'),
	new snook.player ("Ben Hancorn", "", 'ENG'),
	new snook.player ("Ben Harrison", "", 'ENG'),
	new snook.player ("Ben Woollaston", "", 'ENG'),
	new snook.player ("Bernard Bennett", "", 'ENG'),
	new snook.player ("Bill Oliver", "", 'ENG'),
	new snook.player ("Billy Joe Castle", "", 'ENG'),
	new snook.player ("Bob Harris", "", 'ENG'),
	new snook.player ("Bradley Jones", "", 'ENG'),
	new snook.player ("Brandon Sargeant", "", 'ENG'),
	new snook.player ("Brian Morgan", "", 'ENG'),
	new snook.player ("Charles Jaques", "", 'ENG'),
	new snook.player ("Chris Henry", "", 'ENG'),
	new snook.player ("Chris Wakelin", "", 'ENG'),
	new snook.player ("Craig Butler", "", 'ENG'),
	new snook.player ("Craig Edwards", "", 'ENG'),
	new snook.player ("Craig Steadman", "", 'ENG'),
	new snook.player ("Darren Clarke", "", 'ENG'),
	new snook.player ("Darryn Walker", "", 'ENG'),
	new snook.player ("Dave Chalmers", "", 'ENG'),
	new snook.player ("Dave Gilbert", "", 'ENG'),
	new snook.player ("Dave Harold", "", 'ENG'),
	new snook.player ("David Gilbert", "", 'ENG'),
	new snook.player ("David Grace", "", 'ENG'),
	new snook.player ("David Greaves", "", 'ENG'),
	new snook.player ("David Lilley", "", 'ENG'),
	new snook.player ("David Roe", "", 'ENG'),
	new snook.player ("David Taylor", "", 'ENG'),
	new snook.player ("Dean Reynolds", "", 'ENG'),
	new snook.player ("Dennis Hughes", "", 'ENG'),
	new snook.player ("Derek Heaton", "", 'ENG'),
	new snook.player ("Doug French", "", 'ENG'),
	new snook.player ("Elliot Slessor", "", 'ENG'),
	new snook.player ("Emma Bonney", "", 'ENG'),
	new snook.player ("Emma Parker", "", 'ENG'),
	new snook.player ("Eric Lawlor", "", 'ENG'),
	new snook.player ("Evelyn Morland-Smith", "", 'ENG'),
	new snook.player ("Fred Davis", "Fred Davis (snookerzysta)", 'ENG'),
	new snook.player ("Fred Lawrence", "", 'ENG'),
	new snook.player ("Gary Ponting", "", 'ENG'),
	new snook.player ("Gary Wilson", "", 'ENG'),
	new snook.player ("Geoff Foulds", "", 'ENG'),
	new snook.player ("Geoff Thompson", "", 'ENG'),
	new snook.player ("George Scott", "", 'ENG'),
	new snook.player ("Graham Cripsey", "", 'ENG'),
	new snook.player ("Hammad Miah", "", 'ENG'),
	new snook.player ("Harvey Chandler", "", 'ENG'),
	new snook.player ("Ian Brumby", "", 'ENG'),
	new snook.player ("Ian Burns", "", 'ENG'),
	new snook.player ("Ian Graham", "", 'ENG'),
	new snook.player ("Ian McCulloch", "", 'ENG'),
	new snook.player ("Ian Williamson", "", 'ENG'),
	new snook.player ("Jack Fitzmaurice", "", 'ENG'),
	new snook.player ("Jack Lisowski", "", 'ENG'),
	new snook.player ("James Cahill", "", 'ENG'),
	new snook.player ("James Leadbetter", "", 'ENG'),
	new snook.player ("James Tatton", "", 'ENG'),
	new snook.player ("Jamie Bodle", "", 'ENG'),
	new snook.player ("Jamie Cope", "", 'ENG'),
	new snook.player ("Jamie Curtis-Barrett", "", 'ENG'),
	new snook.player ("Jamie Hunter", "", 'ENG'),
	new snook.player ("Jamie O'Neill", "Jamie O\u2019Neill", 'ENG'),
	new snook.player ("Jamie Wilson", "", 'ENG'),
	new snook.player ("Jamie Woodman", "", 'ENG'),
	new snook.player ("Jason Smith", "", 'ENG'),
	new snook.player ("Jason Whittaker", "", 'ENG'),
	new snook.player ("Jeff Cundy", "", 'ENG'),
	new snook.player ("Jenson Kendrick", "", 'ENG'),
	new snook.player ("Jim Chambers", "", 'ENG'),
	new snook.player ("Jimmy Michie", "", 'ENG'),
	new snook.player ("Jimmy Robertson", "", 'ENG'),
	new snook.player ("Jimmy White", "", 'ENG'),
	new snook.player ("Joe Davis", "", 'ENG'),
	new snook.player ("Joe O'Connor", "Joe O\u2019Connor", 'ENG'),
	new snook.player ("Joe Perry", "Joe Perry (snookerzysta)", 'ENG'),
	new snook.player ("John Astley", "", 'ENG'),
	new snook.player ("John Barrie", "", 'ENG'),
	new snook.player ("John Hargreaves", "", 'ENG'),
	new snook.player ("John Parrott", "", 'ENG'),
	new snook.player ("John Pulman", "", 'ENG'),
	new snook.player ("John Read", "", 'ENG'),
	new snook.player ("John Spencer", "John Spencer (snookerzysta)", 'ENG'),
	new snook.player ("John Whitty", "", 'ENG'),
	new snook.player ("Johnathan Bagley", "", 'ENG'),
	new snook.player ("Jon Wright", "", 'ENG'),
	new snook.player ("Jonathan Barron", "", 'ENG'),
	new snook.player ("Jonathan Birch", "", 'ENG'),
	new snook.player ("Judd Trump", "", 'ENG'),
	new snook.player ("June Banks", "", 'ENG'),
	new snook.player ("Karl Broughton", "", 'ENG'),
	new snook.player ("Karl Burrows", "", 'ENG'),
	new snook.player ("Karl Payne", "", 'ENG'),
	new snook.player ("Katie Henrick", "", 'ENG'),
	new snook.player ("Kuldesh Johal", "", 'ENG'),
	new snook.player ("Kyren Wilson", "", 'ENG'),
	new snook.player ("Lee Richardson", "", 'ENG'),
	new snook.player ("Les Dodd", "", 'ENG'),
	new snook.player ("Lewis Roberts", "", 'ENG'),
	new snook.player ("Liam Highfield", "", 'ENG'),
	new snook.player ("Louis Heathcote", "", 'ENG'),
	new snook.player ("Luke Fisher", "", 'ENG'),
	new snook.player ("Luke Simmonds", "", 'ENG'),
	new snook.player ("Malcolm Bradley", "", 'ENG'),
	new snook.player ("Maria Catalano", "", 'ENG'),
	new snook.player ("Mark Davis", "Mark Davis (snookerzysta)", 'ENG'),
	new snook.player ("Mark Gray", "", 'ENG'),
	new snook.player ("Mark Johnston-Allen", "", 'ENG'),
	new snook.player ("Mark Joyce", "", 'ENG'),
	new snook.player ("Mark King", "Mark King (snookerzysta)", 'ENG'),
	new snook.player ("Mark Rowing", "", 'ENG'),
	new snook.player ("Mark Selby", "", 'ENG'),
	new snook.player ("Martin Clark", "", 'ENG'),
	new snook.player ("Martin Gould", "", 'ENG'),
	new snook.player ("Martin O'Donnell", "Martin O\u2019Donnell", 'ENG'),
	new snook.player ("Martin Smith", "", 'ENG'),
	new snook.player ("Matthew Selt", "", 'ENG'),
	new snook.player ("Maurice Parkin", "", 'ENG'),
	new snook.player ("Melbourne Inman", "", 'ENG'),
	new snook.player ("Michael Holt", "Michael Holt (snookerzysta)", 'ENG'),
	new snook.player ("Michael Rhodes", "", 'ENG'),
	new snook.player ("Michael Wild", "", 'ENG'),
	new snook.player ("Michalis Georgiou", "Michael Georgiou", 'ENG'),
	new snook.player ("Mick Fisher", "", 'ENG'),
	new snook.player ("Mike Darrington", "", 'ENG'),
	new snook.player ("Mike Dunn", "", 'ENG'),
	new snook.player ("Mike Hallett", "", 'ENG'),
	new snook.player ("Mitchell Mann", "", 'ENG'),
	new snook.player ("Munraj Pal", "", 'ENG'),
	new snook.player ("Neal Foulds", "", 'ENG'),
	new snook.player ("Neil Mosley", "", 'ENG'),
	new snook.player ("Nick Terry", "", 'ENG'),
	new snook.player ("Nick Walker", "", 'ENG'),
	new snook.player ("Nicolas Pearce", "", 'ENG'),
	new snook.player ("Nigel Bond", "", 'ENG'),
	new snook.player ("Nigel Gilbert", "", 'ENG'),
	new snook.player ("Oliver Brown", "", 'ENG'),
	new snook.player ("Oliver King", "", 'ENG'),
	new snook.player ("Oliver Lines", "", 'ENG'),
	new snook.player ("Paul Cavney", "", 'ENG'),
	new snook.player ("Paul Davison", "", 'ENG'),
	new snook.player ("Paul Gibson", "", 'ENG'),
	new snook.player ("Paul Hunter", "", 'ENG'),
	new snook.player ("Paul Sweeny", "", 'ENG'),
	new snook.player ("Paul Wykes", "", 'ENG'),
	new snook.player ("Peter Devlin", "", 'ENG'),
	new snook.player ("Peter Ebdon", "", 'ENG'),
	new snook.player ("Peter Gilchrist", "", 'ENG'),
	new snook.player ("Peter Lines", "", 'ENG'),
	new snook.player ("Reanne Evans", "", 'ENG'),
	new snook.player ("Rebecca Kenna", "", 'ENG'),
	new snook.player ("Richard Somauroo", "", 'ENG'),
	new snook.player ("Ricky Walden", "", 'ENG'),
	new snook.player ("Riley Parsons", "", 'ENG'),
	new snook.player ("Robbie Williams", "", 'ENG'),
	new snook.player ("Robert Marshall", "", 'ENG'),
	new snook.player ("Robert Milkins", "", 'ENG'),
	new snook.player ("Rod Lawler", "", 'ENG'),
	new snook.player ("Roger Baksa", "", 'ENG'),
	new snook.player ("Roger Bales", "", 'ENG'),
	new snook.player ("Ron Gross", "", 'ENG'),
	new snook.player ("Ronnie O'Sullivan", "Ronnie O\u2019Sullivan", 'ENG'),
	new snook.player ("Rory McLeod", "", 'ENG'),
	new snook.player ("Ryan Clark", "", 'ENG'),
	new snook.player ("Sam Baird", "", 'ENG'),
	new snook.player ("Sam Craigie", "", 'ENG'),
	new snook.player ("Sanderson Lam", "", 'ENG'),
	new snook.player ("Sean Lanigan", "", 'ENG'),
	new snook.player ("Sean Maddocks", "", 'ENG'),
	new snook.player ("Sean O'Sullivan", "", 'ENG'),
	new snook.player ("Sean Storey", "", 'ENG'),
	new snook.player ("Shaun Murphy", "", 'ENG'),
	new snook.player ("Simon Bedford", "", 'ENG'),
	new snook.player ("Stan Moody", "", 'ENG'),
	new snook.player ("Stephen Craigie", "", 'ENG'),
	new snook.player ("Stephen Lee", "", 'ENG'),
	new snook.player ("Stephen Rowlings", "", 'ENG'),
	new snook.player ("Steve Campbell", "", 'ENG'),
	new snook.player ("Steve Davis", "", 'ENG'),
	new snook.player ("Steve Duggan", "", 'ENG'),
	new snook.player ("Steve Judd", "", 'ENG'),
	new snook.player ("Steve Meakin", "", 'ENG'),
	new snook.player ("Steven Hallworth", "", 'ENG'),
	new snook.player ("Stuart Bingham", "", 'ENG'),
	new snook.player ("Stuart Mann", "", 'ENG'),
	new snook.player ("Stuart Reardon", "", 'ENG'),
	new snook.player ("Terry Whitthread", "", 'ENG'),
	new snook.player ("Tom Dennis", "", 'ENG'),
	new snook.player ("Tom Ford", "Tom Ford (snookerzysta)", 'ENG'),
	new snook.player ("Tom Newman", "", 'ENG'),
	new snook.player ("Tony Jones", "", 'ENG'),
	new snook.player ("Tony Knowles", "", 'ENG'),
	new snook.player ("Troy Shaw", "", 'ENG'),
	new snook.player ("Vera Selby", "", 'ENG'),
	new snook.player ("Wayne Brown", "", 'ENG'),
	new snook.player ("Wayne Cooper", "", 'ENG'),
	new snook.player ("Willie Thorne", "", 'ENG'),
	new snook.player ("Zak Surety", "", 'ENG'),

	new snook.player ("Tetiana Vekker", "", 'UKR'),

	new snook.player ("Alan Burnett", "", 'SCO'),
	new snook.player ("Alan McManus", "", 'SCO'),
	new snook.player ("Anthony McGill", "", 'SCO'),
	new snook.player ("Billy Snaddon", "", 'SCO'),
	new snook.player ("Chris Ross", "", 'SCO'),
	new snook.player ("Chris Small", "", 'SCO'),
	new snook.player ("Chris Totten", "", 'SCO'),
	new snook.player ("Craig McGillivray", "", 'SCO'),
	new snook.player ("David McLellan", "", 'SCO'),
	new snook.player ("David Sneddon", "", 'SCO'),
	new snook.player ("Dean Young", "", 'SCO'),
	new snook.player ("Drew Henry", "", 'SCO'),
	new snook.player ("Duncan Campbell", "", 'SCO'),
	new snook.player ("Eddie McLaughlin", "", 'SCO'),
	new snook.player ("Eddie Sinclair", "", 'SCO'),
	new snook.player ("Eden Sharav", "", 'SCO'),
	new snook.player ("Euan Henderson", "", 'SCO'),
	new snook.player ("Fraser Patrick", "", 'SCO'),
	new snook.player ("Gary Thomson", "", 'SCO'),
	new snook.player ("Graeme Dott", "", 'SCO'),
	new snook.player ("Graham Horne", "", 'SCO'),
	new snook.player ("Hugh Abernethy", "", 'SCO'),
	new snook.player ("Ian Black", "", 'SCO'),
	new snook.player ("James McBain", "", 'SCO'),
	new snook.player ("Jamie Burnett", "", 'SCO'),
	new snook.player ("Jim Donnelly", "", 'SCO'),
	new snook.player ("John Higgins", "", 'SCO'),
	new snook.player ("John Lardner", "", 'SCO'),
	new snook.player ("John Phillips", "", 'SCO'),
	new snook.player ("John Rea", "", 'SCO'),
	new snook.player ("Liam Graham", "", 'SCO'),
	new snook.player ("Marcus Campbell", "", 'SCO'),
	new snook.player ("Mark Boyle", "", 'SCO'),
	new snook.player ("Martin Dziewialtowski", "", 'SCO'),
	new snook.player ("Matt Gibson", "", 'SCO'),
	new snook.player ("Michael Collumb", "", 'SCO'),
	new snook.player ("Michael Maguire", "", 'SCO'),
	new snook.player ("Murdo MacLeod", "", 'SCO'),
	new snook.player ("Paul McPhillips", "", 'SCO'),
	new snook.player ("Rhys Clark", "", 'SCO'),
	new snook.player ("Robert Carlisle", "", 'SCO'),
	new snook.player ("Robert Shanks", "", 'SCO'),
	new snook.player ("Robert Stephen", "", 'SCO'),
	new snook.player ("Ross Muir", "", 'SCO'),
	new snook.player ("Scott Donaldson", "", 'SCO'),
	new snook.player ("Scott MacKenzie", "", 'SCO'),
	new snook.player ("Stephen Hendry", "", 'SCO'),
	new snook.player ("Steven Bennie", "", 'SCO'),
	new snook.player ("Walter Donaldson", "Walter Donaldson (snookerzysta)", 'SCO'),

	new snook.player ("Mehmet Husnu", "", 'CYP'),
	new snook.player ("Michalis Georgiou", "Michael Georgiou", 'CYP'),

	new snook.player ("Agnes Davies", "", 'WAL'),
	new snook.player ("Alwyn Lloyd", "", 'WAL'),
	new snook.player ("Andrew Pagett", "", 'WAL'),
	new snook.player ("Anthony Davies", "", 'WAL'),
	new snook.player ("Cliff Wilson", "", 'WAL'),
	new snook.player ("Clive Everton", "", 'WAL'),
	new snook.player ("Daniel Wells", "", 'WAL'),
	new snook.player ("Darren Morgan", "", 'WAL'),
	new snook.player ("David John", "", 'WAL'),
	new snook.player ("Dominic Dale", "", 'WAL'),
	new snook.player ("Doug Mountjoy", "", 'WAL'),
	new snook.player ("Duane Jones", "", 'WAL'),
	new snook.player ("Dylan Emery", "", 'WAL'),
	new snook.player ("Eirian Williams", "", 'WAL'),
	new snook.player ("Gareth Allen", "", 'WAL'),
	new snook.player ("Gareth Coppack", "", 'WAL'),
	new snook.player ("Gary Owen", "", 'WAL'),
	new snook.player ("Ian Preece", "", 'WAL'),
	new snook.player ("Jackson Page", "", 'WAL'),
	new snook.player ("Jak Jones", "", 'WAL'),
	new snook.player ("Jamie Clarke", "", 'WAL'),
	new snook.player ("Jamie Jones", "", 'WAL'),
	new snook.player ("Kishan Hirani", "", 'WAL'),
	new snook.player ("Lee Walker", "", 'WAL'),
	new snook.player ("Marcus Owen", "", 'WAL'),
	new snook.player ("Mark Bennett", "", 'WAL'),
	new snook.player ("Mark Fenton", "", 'WAL'),
	new snook.player ("Mark Williams", "Mark J. Williams", 'WAL'),
	new snook.player ("Matthew Stevens", "", 'WAL'),
	new snook.player ("Michael White", "Michael White (snookerzysta)", 'WAL'),
	new snook.player ("Paul Davies", "Paul Davies (snookerzysta)", 'WAL'),
	new snook.player ("Philip Williams", "", 'WAL'),
	new snook.player ("Ray Reardon", "", 'WAL'),
	new snook.player ("Ron Jones", "", 'WAL'),
	new snook.player ("Roy Andrewartha", "", 'WAL'),
	new snook.player ("Ryan Day", "", 'WAL'),
	new snook.player ("Steve Newbury", "", 'WAL'),
	new snook.player ("Terry Griffiths", "", 'WAL'),
	new snook.player ("Terry Parsons", "", 'WAL'),
	new snook.player ("Tom Carpenter", "", 'WAL'),
	new snook.player ("Tony Chappel", "", 'WAL'),
	new snook.player ("Tyler Rees", "", 'WAL'),
	new snook.player ("Wayne Jones", "", 'WAL'),

	new snook.player ("Peter Francisco", "", 'ZAF'),

	new snook.player ("Alex Higgins", "", 'NIR'),
	new snook.player ("Declan Hughes", "", 'NIR'),
	new snook.player ("Dermot McGlinchey", "", 'NIR'),
	new snook.player ("Gerard Greene", "", 'NIR'),
	new snook.player ("Joe Swail", "", 'NIR'),
	new snook.player ("Jordan Brown", "", 'NIR'),
	new snook.player ("Karen Corr", "", 'NIR'),
	new snook.player ("Mark Allen", "Mark Allen (snookerzysta)", 'NIR'),
	new snook.player ("Robbie McGuigan", "", 'NIR'),
	new snook.player ("Sean O'Neill", "", 'NIR'),
	new snook.player ("Tommy Murphy", "", 'NIR'),

	new snook.player ("Joe Brady", "", 'IRL'),
	new snook.player ("Joe O'Boye", "", 'IRL'),

	new snook.player ("Chris Henry", "", 'BEL'),

	new snook.player ("Robin Hull", "", 'FIN'),

	new snook.player ("Peter Gilchrist", "", 'SGP'),

	new snook.player ("Gary Owen", "", 'AUS'),
	new snook.player ("Philip Tarrant", "", 'AUS'),

	new snook.player ("Aditya Mehta", "", 'IND'),
	new snook.player ("Brijesh Damani", "", 'IND'),
	new snook.player ("Geet Sethi", "", 'IND'),
	new snook.player ("Pankaj Advani", "", 'IND'),

	new snook.player ("Rory McLeod", "", 'JAM'),

	new snook.player ("Aaron Canavan", "", 'JEY'),

	new snook.player ("Amir Sarkhosh", "", 'IRN'),

	new snook.player ("Eden Sharav", "", 'ISR'),

	new snook.player ("Farakh Ajaib", "", 'PAK'),

	new snook.player ("Andy Lee", "", 'HKG'),
	new snook.player ("Au Chi-wai", "", 'HKG'),
	new snook.player ("Fung Kwok Wai", "", 'HKG'),
	new snook.player ("Ka Wai Cheung", "", 'HKG'),
	new snook.player ("Marco Fu", "", 'HKG'),
	new snook.player ("Ng On Yee", "", 'HKG'),

	new snook.player ("Darryl Hill", "", 'IMN')
];